id: P009310
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS20558
  title: སྲིན་པོ་རྐང་བཀྲའི་གཏམ་རྒྱུད།
  author: ''
  volumes:
    78bd6ff159d4461ebda2e7ba026a1068:
      image_group_id: I8LS20560
      title: ''
      volume_number: 1
      total_pages: 163
      base_file: v001.txt
